### ISSUE TITLE
infografa

### ISSUE THREAD

**Issue by Azucena-Tejeda** [SistemasTecTlaxiaco/infografia-de-las-librerias-Azucena-Tejeda#2]
[Infografia-Azucena Lopez Tejeda.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Azucena-Tejeda/files/6341201/Infografia-Azucena.Lopez.Tejeda.pdf)

**Comment by IsaHuerta23** [comment]
Calificación: 18/20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
